{
 "title": "Data Quality",
 "description": "A dashboard to monitor quality of ingested data.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Error Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', date) AS hour_interval, AVG(percentage) as error_ratio\nFROM data_quality_errors\nGROUP BY 1;"
    }
   ]
  },
  {
   "title": "Most Common Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT(rule) as unique_rule, COUNT(*) AS error_count\nFROM data_quality_errors\nWHERE criticality > 1\nGROUP BY unique_rule\nORDER BY error_count DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Average Error Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', date) AS hour_interval,\n       AVG(percentage) AS avg_error_rate\nFROM data_quality_errors\nGROUP BY hour_interval\nORDER BY hour_interval;"
    }
   ]
  },
  {
   "title": "Number of Errors over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', date) as hour, COUNT(*) AS number_of_errors\nFROM data_quality_errors\nGROUP BY 1\nORDER BY 2 DESC;"
    }
   ]
  },
  {
   "title": "Number of Rows with Error over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date, (missing_values+rows) as total_rows, (missing_values) as rows_with_errors\nFROM data_quality_errors;"
    }
   ]
  }
 ]
}