{
 "title": "Walmart Sales prediction Dashboard for Engineers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GEN VIZ 1 : Total Num of Entries in DB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM features LIMIT 50 "
    }
   ]
  },
  {
   "title": "PRED VIZ 2 : Average prediction in last 1 day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"Sales\") As \"Average Prediction\" FROM features\r\nWHERE TO_TIMESTAMP(pred_date, 'YYYY-MM-DD HH24:MI:SS.US') >= NOW() - INTERVAL '1 day'\r\n"
    }
   ]
  },
  {
   "title": "DATA DRIFT VIZ 1 - Data Drift in Features",
   "type": "stat",
   "description": "to detect the data drift in features used while training.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    AVG(ABS(train.\"Temperature\" - test.\"Temperature\")) AS average_temperature_drift,\r\n    AVG(ABS(train.\"Fuel_Price\" - test.\"Fuel_Price\")) AS average_fuel_price_drift,\r\n    AVG(ABS(train.\"Unemployment\" - test.\"Unemployment\")) AS average_unemployment_drift,\r\n    AVG(ABS(CAST(train.\"IsHoliday\" AS INTEGER) - CAST(test.\"IsHoliday\" AS INTEGER))) AS average_is_holiday_drift\r\nFROM\r\n    metrics_average AS train,\r\n    features AS test;"
    }
   ]
  },
  { "title": "ALERTS", "type": "alertlist", "gridPos": { "h": 18, "w": 12, "x": 12, "y": 8 } },
  {
   "title": "DATA DRIFT VIZ 2 - Data Drift With correlation",
   "type": "bargauge",
   "description": "Correlation between features and Sales to study current data environment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CORR(features.\"Sales\", features.\"Fuel_Price\") AS fuel_price_corr,\r\n    CORR(features.\"Sales\", features.\"Unemployment\") AS unemployment_corr,\r\n    CORR(features.\"Sales\", features.\"Temperature\") AS temperature_corr,\r\n    CORR(features.\"Sales\", features.\"CPI\") AS cpi_corr\r\nFROM\r\n    features;"
    }
   ]
  }
 ]
}